name: Cypress Tests

on:
  workflow_dispatch:  
    branches:
      - main       

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Pegar o código do repositório
      - uses: actions/checkout@v3

      # Instalar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Instalar dependências
      - name: Install dependencies
        run: npm ci

      # Rodar testes Cypress
      - name: Run Cypress tests
        run: npx cypress run

