pipeline {
    agent any
    stages {
        stage('Login') {
            steps {
                sh 'npx cypress run --spec "cypress/e2e/login.cy.js"'
            }
        }
        stage('Home') {
            steps {
                sh 'npx cypress run --spec "cypress/e2e/home.cy.js"'
            }
        }
        stage('Xsolla') {
            steps {
                sh 'npx cypress run --spec "cypress/e2e/xsolla.cy.js"'
            }
        }
    }
}
