name: Loja Web Praia Bingo

on:
  workflow_dispatch: 
  push:              
  pull_request:      

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes Cypress
        run: npx cypress run

