name: Loja Web Praia Bingo

on:
  workflow_dispatch: # permite rodar manualmente
  push:              # roda ao fazer push
  pull_request:      # roda em PR

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências do Ubuntu
        run: sudo apt-get update && sudo apt-get install -y \
          libgtk2.0-0 libgt


